
name: FPGA Verification

on: [push, pull_request]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Icarus Verilog
      run: sudo apt-get install -y iverilog

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Cocotb & Matplotlib
      run: pip install cocotb cocotb-test matplotlib

    - name: Run Tests
      run: |
        cd tb
        # GUI açılmaması için MPLBACKEND ayarı yapıyoruz
        export MPLBACKEND=Agg 
        python run.py
